title: TrustBench
description: Security Compliance Benchmark for LLMs
baseurl: "/trustbench"
url: "https://varungurnaney.github.io"
theme: null
plugins:
  - jekyll-seo-tag

exclude:
  - trustbench/
  - tasks/
  - schema/
  - pyproject.toml
  - requirements.txt
  - eval.py
  - blog-draft.md
  - "*.json"
